export const INVOLVED_OBJ = {
  "2022.09-2022.10": "코드스테이츠 39기 프로젝트 프론트엔드 멘토 참여",
  "2022.11-2022.12": "코드스테이츠 40기 프로젝트 프론트엔드 멘토 참여",
  "2023.01-2023.02": "코드스테이츠 41기 프로젝트 프론트엔드 멘토 참여",
  "2023.03-2023.04": "코드스테이츠 42기 프로젝트 프론트엔드 멘토 참여",
  "2023.04-2023.05": "코드스테이츠 43기 프로젝트 프론트엔드 멘토 참여",
  "2023.06-2023.07": "코드스테이츠 44기 프로젝트 프론트엔드 멘토 참여",
  "2023.08-2023.09": "코드스테이츠 45기 프로젝트 프론트엔드 멘토 참여",
};

export const PROJECT_LIST = [
  {
    id: 1,
    title: "나만의 공통 컴포넌트",
    desc: "주로 사용되는 공통컴포넌트를 제작하여 npm 에 배포하여 모노레포로 사용 가능합니다. ",
    code: "customCommonComponent",
    stack: ["react", "typescript", "tailwindcss", "vite", "npm"],
    link: "https://www.npmjs.com/package/react-ts-sook-ui",
    img: "/projects/mandalart.png",
  },
  //{
  //  id: 2,
  //  title: "3D 규섭이",
  //  desc: "사내 캐릭터 규섭이를 R3F 로 구현했습니다.",
  //  code: "portfolio",
  //  stack: ["react", "react-three-fiber", "emotion", "vite"],
  //  link: "https://next-sookdev.vercel.app/",
  //},
  {
    id: 2,
    title: "만다라트",
    desc: "성공적인 계획 실행을 위한 만다라트 계획표를 만들었습니다.",
    code: "mandalart",
    stack: ["react", "tailwindcss", "vite"],
    link: "https://mandalart-plan.vercel.app/",
    img: "/projects/mandalart.png",
  },
  {
    id: 3,
    title: "청첩장",
    desc: "고객이 커스터마이징이 가능한 모바일 청첩장을 제작했습니다.",
    code: "weddingCard",
    stack: ["next.js", "typescript", "tailwindcss", "vite", "react-hook-form"],
    link: "-",
    img: "/projects/mandalart.png",
  },
  {
    id: 4,
    title: "SookDev 블로그",
    desc: "기존 개츠비에서 운영하던 블로그에서 Next.js 앱라우터 버전으로 마이그레이션 한 테크 기록 블로그 입니다.",
    code: "sookDevBlog",
    stack: ["next.js", "javascript", "tailwindcss", "github-action", "vercel"],
    link: "/",
    img: "/projects/mandalart.png",
  },
];
